/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progex.zoomanagementsoftware.zookeeper;

import com.progex.zoomanagementsoftware.datatypes.Methods;
import com.progex.zoomanagementsoftware.main.MainMenuJFrame;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author khalid
 */
public class NächsteFütterungJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NächsteFütterungJFrame
     */
    public NächsteFütterungJFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);        

        Methods methods = new Methods();
        methods.showTimeAndDate(jLabelNächsteFütterungDatum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelNächsteFütterungFutter = new javax.swing.JLabel();
        jLabelNächsteFütterungFutterMenge = new javax.swing.JLabel();
        jLabelNächsteFütterungTiername = new javax.swing.JLabel();
        jLabelNächsteFütterungGehgename = new javax.swing.JLabel();
        jLabelNächsteFütterungAbstellRaum = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelNächsteFütterungDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setText("Zurück");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 81, -1));

        jButton2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton2.setText("Abmelden");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Nächste Fütterung in");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 52, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Futter:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Futtermenge:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 146, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Tiername:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 187, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Gehege:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 228, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Abstellraum:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 269, 98, -1));

        jLabelNächsteFütterungFutter.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungFutter, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 105, -1, -1));

        jLabelNächsteFütterungFutterMenge.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungFutterMenge, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 146, -1, -1));

        jLabelNächsteFütterungTiername.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungTiername, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 187, -1, -1));

        jLabelNächsteFütterungGehgename.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungGehgename, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 228, -1, -1));

        jLabelNächsteFütterungAbstellRaum.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungAbstellRaum, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 269, -1, -1));

        jButton3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton3.setText("Alle Fütterungen anzeigen");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 529, 57));

        jLabelNächsteFütterungDatum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(jLabelNächsteFütterungDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        new AlleFütterungenJFrame().setVisible(true); // open AlleFütterungen JFrame
        this.dispose();//to close the current jframe

        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose(); //close current JFrame
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new ZookeeperModeHomePageJFrame().setVisible(true); // Go back ZooKeeperHomePage
        this.dispose(); // close current JFrame
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NächsteFütterungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NächsteFütterungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NächsteFütterungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NächsteFütterungJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NächsteFütterungJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNächsteFütterungAbstellRaum;
    private javax.swing.JLabel jLabelNächsteFütterungDatum;
    private javax.swing.JLabel jLabelNächsteFütterungFutter;
    private javax.swing.JLabel jLabelNächsteFütterungFutterMenge;
    private javax.swing.JLabel jLabelNächsteFütterungGehgename;
    private javax.swing.JLabel jLabelNächsteFütterungTiername;
    // End of variables declaration//GEN-END:variables
}
