/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progex.zoomanagementsoftware.zookeeper;

import com.progex.zoomanagementsoftware.main.MainMenuJFrame;
import javax.swing.JFrame;

/**
 *
 * @author khali
 */
public class ZookeeperModeHomePageJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ZookeeperModeHomePage
     */
    public ZookeeperModeHomePageJFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonMeineNächsteFütterungZookeeper = new javax.swing.JButton();
        jButtonAlleFütterungenFürHeuteZookeeper = new javax.swing.JButton();
        jLabelZookeeperHomePageLetzteAnmeldungUhrzeit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelZookeeperHomePageNächsteFütterung = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelZooKeeperHomePageTierpflegerName = new javax.swing.JLabel();
        jLabelZookeeperModeHomePageDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Letze Anmeldung: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 156, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setText("Abmelden");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 11, 103, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Hallo ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 45, -1, -1));

        jButtonMeineNächsteFütterungZookeeper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButtonMeineNächsteFütterungZookeeper.setText("Meine Nächste Fütterung ");
        jButtonMeineNächsteFütterungZookeeper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMeineNächsteFütterungZookeeperMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonMeineNächsteFütterungZookeeper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 377, 81));

        jButtonAlleFütterungenFürHeuteZookeeper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButtonAlleFütterungenFürHeuteZookeeper.setText("Alle Fütterungen für heute");
        jButtonAlleFütterungenFürHeuteZookeeper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlleFütterungenFürHeuteZookeeperMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAlleFütterungenFürHeuteZookeeper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 377, 77));

        jLabelZookeeperHomePageLetzteAnmeldungUhrzeit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(jLabelZookeeperHomePageLetzteAnmeldungUhrzeit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 11, 14, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Nächste Fütterung in: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 171, -1));

        jLabelZookeeperHomePageNächsteFütterung.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelZookeeperHomePageNächsteFütterung, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 92, 5, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 92, 5, -1));

        jLabelZooKeeperHomePageTierpflegerName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        getContentPane().add(jLabelZooKeeperHomePageTierpflegerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 45, -1, -1));

        jLabelZookeeperModeHomePageDatum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(jLabelZookeeperModeHomePageDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 17, 47, 16));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonMeineNächsteFütterungZookeeperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMeineNächsteFütterungZookeeperMouseClicked
        // TODO add your handling code here:
        new NächsteFütterungJFrame().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonMeineNächsteFütterungZookeeperMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosed

    private void jButtonAlleFütterungenFürHeuteZookeeperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlleFütterungenFürHeuteZookeeperMouseClicked
        // TODO add your handling code here:
        new AlleFütterungenJFrame().setVisible(true);
      //  this.setVisible(false);
        
    }//GEN-LAST:event_jButtonAlleFütterungenFürHeuteZookeeperMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZookeeperModeHomePageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZookeeperModeHomePageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZookeeperModeHomePageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZookeeperModeHomePageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZookeeperModeHomePageJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlleFütterungenFürHeuteZookeeper;
    private javax.swing.JButton jButtonMeineNächsteFütterungZookeeper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelZooKeeperHomePageTierpflegerName;
    private javax.swing.JLabel jLabelZookeeperHomePageLetzteAnmeldungUhrzeit;
    private javax.swing.JLabel jLabelZookeeperHomePageNächsteFütterung;
    private javax.swing.JLabel jLabelZookeeperModeHomePageDatum;
    // End of variables declaration//GEN-END:variables
}
