/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progex.zoomanagementsoftware.guest;
import com.progex.zoomanagementsoftware.datatypes.Methods;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oLLii
 */
public class AuswahvonListelJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AuswahlJFrame
     */
    public AuswahvonListelJFrame() {
        initComponents();
        myInitComponents();
    }
    
    public void myInitComponents(){
        
        Methods methods = new Methods();    
        methods.showTimeAndDate(jLabelShowDateTime);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonZurueck = new javax.swing.JButton();
        jLabelShowDateTime = new javax.swing.JLabel();
        jLabelTiername = new javax.swing.JLabel();
        jLabelZeit = new javax.swing.JLabel();
        jLabelstatic = new javax.swing.JLabel();
        jLabelGehege = new javax.swing.JLabel();
        jLabelstatic1 = new javax.swing.JLabel();
        jLabelFutter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonZurueck.setText("Zurück");

        jLabelShowDateTime.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelShowDateTime.setText("TIME");

        jLabelTiername.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTiername.setText("Tiername :");

        jLabelZeit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelZeit.setText("Zeit XX:XX -XX:XX");

        jLabelstatic.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelstatic.setText("Gehege:");

        jLabelGehege.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelGehege.setText("xxx Gehege");

        jLabelstatic1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelstatic1.setText("Futter:");

        jLabelFutter.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelFutter.setText("xxx Futter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonZurueck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelShowDateTime)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelstatic1)
                    .addComponent(jLabelstatic)
                    .addComponent(jLabelTiername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZeit)
                    .addComponent(jLabelGehege)
                    .addComponent(jLabelFutter))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZurueck)
                    .addComponent(jLabelShowDateTime))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiername)
                    .addComponent(jLabelZeit))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstatic)
                    .addComponent(jLabelGehege))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstatic1)
                    .addComponent(jLabelFutter))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuswahvonListelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuswahvonListelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuswahvonListelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuswahvonListelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuswahvonListelJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZurueck;
    private javax.swing.JLabel jLabelFutter;
    private javax.swing.JLabel jLabelGehege;
    private javax.swing.JLabel jLabelShowDateTime;
    private javax.swing.JLabel jLabelTiername;
    private javax.swing.JLabel jLabelZeit;
    private javax.swing.JLabel jLabelstatic;
    private javax.swing.JLabel jLabelstatic1;
    // End of variables declaration//GEN-END:variables
}
