/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progex.zoomanagementsoftware.main;

/**
 *
 * @author khali
 */
public class AlleFütterungenJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NächsteFütterungJFrame
     */
    public AlleFütterungenJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlleFütterungLogout = new javax.swing.JButton();
        jButtonAlleFütterungenNächsteFütterungAnzeigen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlleFütterungen = new javax.swing.JTable();
        jRadioButtonAlleFütterungenInKilogramm = new javax.swing.JRadioButton();
        jRadioButtonAlleFütterungenInGramm = new javax.swing.JRadioButton();
        jLabelAlleFütterungenUhrzeit = new javax.swing.JLabel();
        jButtonAlleFütterungenZurück = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAlleFütterungLogout.setText("Abmelden");
        jButtonAlleFütterungLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlleFütterungLogoutActionPerformed(evt);
            }
        });

        jButtonAlleFütterungenNächsteFütterungAnzeigen.setText("Nächste Fütterung anzeigen");

        jTableAlleFütterungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fütterungszeit", "Tiername", "Futter", "Futtermenge", "Abstellraum", "Gehege"
            }
        ));
        jScrollPane1.setViewportView(jTableAlleFütterungen);

        jRadioButtonAlleFütterungenInKilogramm.setText("Futtermenge in Kilogramm");
        jRadioButtonAlleFütterungenInKilogramm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlleFütterungenInKilogrammActionPerformed(evt);
            }
        });

        jRadioButtonAlleFütterungenInGramm.setText("Futtermenge in Gramm");
        jRadioButtonAlleFütterungenInGramm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlleFütterungenInGrammActionPerformed(evt);
            }
        });

        jLabelAlleFütterungenUhrzeit.setText("Datum");
        jLabelAlleFütterungenUhrzeit.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelAlleFütterungenUhrzeitAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButtonAlleFütterungenZurück.setText("Zurück");
        jButtonAlleFütterungenZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlleFütterungenZurückActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlleFütterungenNächsteFütterungAnzeigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAlleFütterungenZurück)
                        .addGap(159, 159, 159)
                        .addComponent(jLabelAlleFütterungenUhrzeit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlleFütterungLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonAlleFütterungenInKilogramm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonAlleFütterungenInGramm)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlleFütterungLogout)
                    .addComponent(jButtonAlleFütterungenZurück)
                    .addComponent(jLabelAlleFütterungenUhrzeit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAlleFütterungenInGramm)
                    .addComponent(jRadioButtonAlleFütterungenInKilogramm))
                .addGap(18, 18, 18)
                .addComponent(jButtonAlleFütterungenNächsteFütterungAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlleFütterungLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlleFütterungLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlleFütterungLogoutActionPerformed

    private void jRadioButtonAlleFütterungenInKilogrammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlleFütterungenInKilogrammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAlleFütterungenInKilogrammActionPerformed

    private void jRadioButtonAlleFütterungenInGrammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlleFütterungenInGrammActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAlleFütterungenInGrammActionPerformed

    private void jLabelAlleFütterungenUhrzeitAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelAlleFütterungenUhrzeitAncestorAdded
        // TODO add your handlig code here:
    }//GEN-LAST:event_jLabelAlleFütterungenUhrzeitAncestorAdded

    private void jButtonAlleFütterungenZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlleFütterungenZurückActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlleFütterungenZurückActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlleFütterungenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlleFütterungenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlleFütterungenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlleFütterungenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlleFütterungenJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlleFütterungLogout;
    private javax.swing.JButton jButtonAlleFütterungenNächsteFütterungAnzeigen;
    private javax.swing.JButton jButtonAlleFütterungenZurück;
    private javax.swing.JLabel jLabelAlleFütterungenUhrzeit;
    private javax.swing.JRadioButton jRadioButtonAlleFütterungenInGramm;
    private javax.swing.JRadioButton jRadioButtonAlleFütterungenInKilogramm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlleFütterungen;
    // End of variables declaration//GEN-END:variables
}
